# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ea98bfbc59e60bd92341721517e2a367"
application_url = "https://occupation-spider-harry-nitrogen.trycloudflare.com"
embedded = true
name = "efficient-conversion-app"
handle = "efficient-conversion-app-9"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products"

[auth]
redirect_urls = [
  "https://occupation-spider-harry-nitrogen.trycloudflare.com/auth/callback",
  "https://occupation-spider-harry-nitrogen.trycloudflare.com/auth/shopify/callback",
  "https://occupation-spider-harry-nitrogen.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
