
const TableOfContents = new Schema({
    resource_type: { type: String, enum: ['collection', 'product', 'page', 'blog_post'], required: true },
    resource_id: { type: String, required: true },
    title: { type: String, default: '' },
    alignment: { type: String, enum: ['left', 'center', 'right'], default: 'left' },
    indentation: { type: Boolean, default: false },
    numbering: { type: String, enum: ['numbers', 'none'], default: 'numbers' },
    section_line: { type: Boolean, default: true },
    headings: { type: [String], default: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] },
    position: { type: String, enum: ['above_first_heading', 'theme_editor', 'custom_class'], default: 'above_first_heading' },
    custom_class_name: { type: String, default: '' },
    scroll_animation: { type: Boolean, default: false },
    scroll_offset: { type: Number, default: 0 },
    font_size_title: { type: Number, default: 14 },
    font_size_headings: { type: Number, default: 14 },
    padding_top: { type: Number, default: 16 },
    padding_bottom: { type: Number, default: 0 },
    padding_left: { type: Number, default: 0 },
    padding_right: { type: Number, default: 0 },
    max_width: { type: Number, default: 0 },
    display_alignment: { type: String, enum: ['center', 'left', 'right'], default: 'center' },
    title_color: { type: String, default: '#000000' },
    heading_color: { type: String, default: '#000000' },
    hide_branding: { type: Boolean, default: true },
    custom_link_hover: { type: Boolean, default: false },
    link_hover_style: { type: String, enum: ['underline', 'none'], default: 'none' },
    heading_id_generation: { type: String, enum: ['numbering', 'slug_by_title'], default: 'numbering' },
    show_hide_button: { type: Boolean, default: true },
    resource_link: { type: String, default: '#' },
    hide_button_name: { type: String, default: 'hide' },
    show_button_name: { type: String, default: 'show' },
    initial_display_lines: { type: Number, default: null },
    show_all_button_name: { type: String, default: 'show all' },
});